const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 333365,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 1000000,
      description: 'high quality product',
    },
    {
      name: 'Archers Voice',
      slug: 'archers-voice-mia-sheridan',
      category: 'Books',
      image: '/images/p5.jpg',
      price: 25,
      countInStock: 6,
      brand: 'Penguin Publishing Group',
      rating: 4.9,
      numReviews: 18,
      description: 'Fall in love with this emotional New York Times bestselling romance between two tortured souls who find their chance at happiness in the most unexpected way. I wanted to lose myself in the small town of Pelion, Maine. To forget everything I had left behind. The sound of rain. The blood.',
    },

  ],
};
export default data;
